### ISSUE TITLE
Detect whether last event was fully written in FSLogStorage

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zb-logstreams#27]
When re-opening ("recovering") a log stream, the last event in the stream may or may not be fully written. (System may have been killed or crashed  in the middle of a write operation).

As part of the log stream opening and closing lifecycle a mechanism for validating the last event needs to be established

**Comment by menski** [comment]
moved to https://github.com/zeebe-io/zeebe/issues/498
