### ISSUE TITLE
Logstream truncate reads position from wrong offset

### ISSUE THREAD

**Issue by menski** [zeebe-io/zb-logstreams#70]
Currently it seems that `logstream.truncate(long position)` does not work as it reads the position of the event from the wrong offset.

The logic of the `LogStreamUtil.LogEntryAddressSupplier` currently:

1. reads the data frame header into a buffer to get the fragment length
2. overrides the buffer with the logged event 
3. reads the event position using the `LogEntryDescriptor.getPosition(buffer, 0)' which expects the data frame header at offset 0, but at offset 0 the LogEntryDescriptor header starts so it reads the wrong position

**Comment by menski** [comment]
After fixing this issue there is another problem. [LogStreamImpl.truncate](https://github.com/camunda-zeebe/zb-logstreams/blob/38a7f2b801dd5ff2ad96fda2c45fd70d7f75d186/src/main/java/io/zeebe/logstreams/impl/LogStreamImpl.java#L330-L335) while initially check the the `logStreamController` is null or fail otherwise. This is only true if never a log stream controller was started. Because if [LogStreamImpl.closeLogStreamController](https://github.com/camunda-zeebe/zb-logstreams/blob/38a7f2b801dd5ff2ad96fda2c45fd70d7f75d186/src/main/java/io/zeebe/logstreams/impl/LogStreamImpl.java#L259-L265) is called the `logStreamController` is not set to null.

This prevents every raft node which at least once was a leader to ever truncate their log afterwards.

I'm note sure what the expected behavior is. As our general concept is reusing objects I would assume that the `logStreamController` should be keep and the check in truncate should instead check if the existing controller is closed? Any comments on this?

**Comment by Zelldon** [comment]
This was removed by rewriting the close behavior, see here https://github.com/camunda-zeebe/zb-logstreams/commit/74c5d47b3501c1cd2c9f9b23a239871fb0fc976e#diff-15c9f5407aa572263a30405205af7768L296 . I think i missed the truncate null check. On openStreamControlling the existing controller is reopened and wraps the writeBuffer, so yeah checking isClosed makes sense.

**Comment by Zelldon** [comment]
## Review
 ### Code

   LogStreamUtil:
  * I'm not quite sure if it is clear for the next developer why we use -HEADER_LENGTH to get the position
  * Maybe we can also improve the `read*` methods. For example to something like this:
```java
        protected boolean readHeader()
        {
            return readIntoBuffer(ioBuffer, 0, HEADER_BLOCK_LENGTH);
        }

        protected boolean readMessage(final int fragmentLength)
        {
            int remainingBytes = fragmentLength;
            while (remainingBytes > 0)
            {
                final int limit = Math.min(remainingBytes, buffer.capacity());
                readIntoBuffer(ioBuffer, HEADER_BLOCK_LENGTH, limit);
                remainingBytes -= limit;
            }
            return true;
        }

        protected boolean readIntoBuffer(ByteBuffer ioBuffer, final int offset, final int limit)
        {
            ioBuffer.position(offset);
            ioBuffer.limit(limit);

            final long opResult = logStorage.read(ioBuffer, nextReadAddress);

            if (opResult >= 0)
            {
                nextReadAddress = opResult;
                return true;
            }

            return false;
        }
```
 * In that case we only overwrite the data segment and can read the position after reading the message.
 * We should have a test that truncates a stream if the LogStreamController is closed

**Comment by menski** [comment]
@Zelldon I tried to do the adjustments (https://github.com/zeebe-io/zb-logstreams/commit/070d0f4ab44e760c3660ccb421ba723f4a01fad4) but I'm struggling to fix the mocked test suite. I'm 50% sure that it works as the raft truncation tests passes but I had to disable some asserts (https://github.com/zeebe-io/zb-logstreams/commit/f6eece35e0ee50d5ab04c809dce10614745238a4) to get the the logstream test suite pass. It would be great if you could explain again to me how these addresses where calculated so I can fix that.

**Comment by menski** [comment]
@Zelldon I also failed to write a test case for truncation after log stream controller close. The issue is that if you open the log stream controller it will try to read to the end. It seems this does not terminate if the mock log stream is initialized with `partlyRead`, which is needed to mock truncation. Maybe you can also help me with this issue, as I currently don't understand how to mock this to make it work. :disappointed:

**Comment by menski** [comment]
Sorry I forgot to link the issue in the commits https://github.com/zeebe-io/zb-logstreams/commit/070d0f4ab44e760c3660ccb421ba723f4a01fad4, https://github.com/zeebe-io/zb-logstreams/commit/010861c6d38e905c875d701f2a98d4548f37abd7, https://github.com/zeebe-io/zb-logstreams/commit/11e6ea5fe6b40e04d5c4008553eefca07ff03943
